<a href="https://colab.research.google.com/github/Hemanthk408/Car_rate_prediction/blob/main/Cars_Rate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import pandas as pd


B=pd.read_json("/content/car_details_bengalur.json")
C=pd.read_json("/content/car_details_chennai.json")
N=pd.read_json("/content/car_details_New_Delhi.json")
J=pd.read_json("/content/car_details_jaipur.json")
P=pd.read_json("/content/car_details_pune.json")

pd.set_option("display.max_columns",None)

# Define the required columns
columns_to_keep = ['title', 'price', 'location', 'Registration Year', 'Insurance',
                   'Fuel Type','Kms Driven', 'RTO', 'Ownership']

# Select only required columns from each dataframe
df1 = B[columns_to_keep]
df2 = C[columns_to_keep]
df3 = N[columns_to_keep]
df4 = J[columns_to_keep]
df5=P[columns_to_keep]

# Merge all dataframes
merged_df = pd.concat([df1, df2, df3, df4,df5], ignore_index=True)

# Save the final dataframe
merged_df.to_csv('merged_data.csv', index=False)

In [ ]:
df=pd.read_csv("/content/merged_data.csv")
df

,title,price,location,Registration Year,Insurance,Fuel Type,Kms Driven,RTO,Ownership
0,2021 Tata Nexon XZA Plus (O) AMT Diesel,₹9.97 Lakh,"Malleswaram, Bangalore",Jan 2021,Comprehensive,Diesel,"12,758 Kms",Bangalore,First Owner
1,2021 Kia Sonet HTX Turbo iMT,₹9.98 Lakh,"Yelahanka, Bangalore",Feb 2021,Comprehensive,Petrol,"9,424 Kms",Bangalore,First Owner
2,2023 Audi Q5 Technology,₹72 Lakh,"R T Nagar, Bangalore",Dec 2023,Comprehensive,Petrol,"3,000 Kms",Bangalore,First Owner
3,2020 Hyundai i20 Asta Turbo iMT,₹8.39 Lakh,"Yelahanka, Bangalore",Nov 2020,Comprehensive,Petrol,"13,539 Kms",Mysore,First Owner
4,2015 Maruti Celerio VXI AT,₹3.65 Lakh,"Btm Layout, Bangalore",Dec 2015,Comprehensive,Petrol,"57,742 Kms",Bangalore,Second Owner
...,...,...,...,...,...,...,...,...,...
2327,2024 Audi Q7 Technology,₹87 Lakh,"Baner, Pune",NaN,Expired,Petrol,"5,000 Kms",NaN,NaN
2328,2021 Nissan Magnite XE,₹5.07 Lakh,"Wagholi, Pune",Oct 2021,Comprehensive,Petrol,"14,276 Kms",Aurangabad,First Owner
2329,2013 Audi A4 2.0 TDI Premium Sport Limited Edi...,₹7.99 Lakh,"Yerwada, Pune",Dec 2013,Comprehensive,Diesel,"75,000 Kms",Pen,Third Owner
2330,2013 Hyundai i20 Petrol Magna,₹2.71 Lakh,"Wakad, Pune",Apr 2013,Comprehensive,Petrol,"48,008 Kms",Nashik,First Owner
2331,2019 Renault Triber RXL BSIV,₹4.25 Lakh,"Thathawade, Pune",Oct 2019,Expired,Petrol,"13,774 Kms",Mumbai,First Owner

In [ ]:
df["location"]=df["location"].str.split(',').str[1]

In [3]:
df=pd.read_excel("/content/ml_dl.xlsx")

In [6]:
df

,city,ft,km,transmission,ownerNo,oem,model,modelYear,variantName,price,Registration Year,Insurance Validity,Seats
0,Kolkata,Petrol,70000,Automatic,3,Toyota,Toyota Camry,2014,Hybrid,975000,2014,Third Party,5
1,Kolkata,Petrol,23981,Manual,1,Datsun,Datsun RediGO,2017,T Option,266000,2017,Comprehensive,5
2,Kolkata,Petrol,7100,Automatic,1,Renault,Renault Kiger,2021,RXT AMT,595000,2021,Comprehensive,5
3,Kolkata,Petrol,71574,Manual,2,Hyundai,Hyundai i20,2011,1.2 Sportz,223000,2012,Third Party,5
4,Kolkata,Diesel,50000,Automatic,2,Audi,Audi Q3,2014,35 TDI Quattro Premium,1200000,2014,Third Party,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8364,Bangalore,Diesel,156039,Manual,2,Toyota,Toyota Fortuner,2012,4x4 MT,1648999,2012,Comprehensive,7
8365,Bangalore,Petrol,56000,Manual,2,Maruti,Maruti SX4,2008,Zxi BSIII,330000,2008,Third Party,5
8366,Bangalore,Petrol,42000,Manual,2,Honda,Honda Brio,2014,S MT,425000,2014,Comprehensive,5
8367,Bangalore,Diesel,93003,Manual,1,Hyundai,Hyundai i20,2018,1.4 Asta Dual Tone,750000,2018,Comprehensive,5
8368,Bangalore,Petrol,36000,Automatic,2,Hyundai,Hyundai Grand i10,2017,Asta Option AT,675000,2017,Comprehensive,5

In [5]:
df=df.drop(["bt","Engine Displacement"],axis=1)

In [8]:
df.isnull().sum()

city                  0
ft                    0
km                    0
transmission          0
ownerNo               0
oem                   0
model                 0
modelYear             0
variantName           0
price                 0
Registration Year     0
Insurance Validity    0
Seats                 0
dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8369 entries, 0 to 8368
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   city                8369 non-null   object
 1   ft                  8369 non-null   object
 2   km                  8369 non-null   int64
 3   transmission        8369 non-null   object
 4   ownerNo             8369 non-null   int64
 5   oem                 8369 non-null   object
 6   model               8369 non-null   object
 7   modelYear           8369 non-null   int64
 8   variantName         8369 non-null   object
 9   price               8369 non-null   int64
 10  Registration Year   8369 non-null   int64
 11  Insurance Validity  8369 non-null   object
 12  Seats               8369 non-null   int64
dtypes: int64(6), object(7)
memory usage: 850.1+ KB

In [9]:
from sklearn.preprocessing import OrdinalEncoder
encoder=OrdinalEncoder()

In [11]:
df.select_dtypes(include="object").columns

Index(['city', 'ft', 'transmission', 'oem', 'model', 'variantName',
       'Insurance Validity'],
      dtype='object')

In [12]:
for i in df.select_dtypes(include='object').columns:
  df[i]=encoder.fit_transform(df[[i]])

In [13]:
df

,city,ft,km,transmission,ownerNo,oem,model,modelYear,variantName,price,Registration Year,Insurance Validity,Seats
0,5.0,4.0,70000,0.0,3,30.0,279.0,2014,1213.0,975000,2014,4.0,5
1,5.0,4.0,23981,1.0,1,4.0,39.0,2017,1683.0,266000,2017,2.0,5
2,5.0,4.0,7100,0.0,1,27.0,239.0,2021,1458.0,595000,2021,2.0,5
3,5.0,4.0,71574,1.0,2,9.0,90.0,2011,149.0,223000,2012,4.0,5
4,5.0,1.0,50000,0.0,2,0.0,7.0,2014,692.0,1200000,2014,4.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8364,0.0,1.0,156039,1.0,2,30.0,285.0,2012,741.0,1648999,2012,2.0,7
8365,0.0,4.0,56000,1.0,2,20.0,177.0,2008,2082.0,330000,2008,4.0,5
8366,0.0,4.0,42000,1.0,2,8.0,61.0,2014,1504.0,425000,2014,2.0,5
8367,0.0,1.0,93003,1.0,1,9.0,90.0,2018,208.0,750000,2018,2.0,5
8368,0.0,4.0,36000,0.0,2,9.0,77.0,2017,864.0,675000,2017,2.0,5

In [14]:
df.corr()

,city,ft,km,transmission,ownerNo,oem,model,modelYear,variantName,price,Registration Year,Insurance Validity,Seats
city,1.000000,-0.014920,-0.020517,0.097957,-0.058144,0.004477,-0.004007,-0.005974,0.051079,-0.075789,-0.007783,0.049108,0.005295
ft,-0.014920,1.000000,-0.165490,0.077116,-0.044848,-0.019222,-0.040365,0.055197,0.065258,-0.181315,0.056964,-0.014626,-0.299714
km,-0.020517,-0.165490,1.000000,0.065439,0.115419,0.015448,0.023288,-0.245030,-0.049889,-0.077351,-0.243921,0.036390,0.074924
transmission,0.097957,0.077116,0.065439,1.000000,0.046777,0.057014,0.040397,-0.196946,0.097972,-0.422600,-0.196864,0.120762,0.008312
ownerNo,-0.058144,-0.044848,0.115419,0.046777,1.000000,-0.040402,-0.030762,-0.390012,-0.062918,-0.120489,-0.390402,0.114257,0.010594
oem,0.004477,-0.019222,0.015448,0.057014,-0.040402,1.000000,0.988939,0.091536,-0.002543,-0.034547,0.090081,0.037936,0.134449
model,-0.004007,-0.040365,0.023288,0.040397,-0.030762,0.988939,1.000000,0.074859,-0.023676,-0.007771,0.073661,0.033188,0.132111
modelYear,-0.005974,0.055197,-0.245030,-0.196946,-0.390012,0.091536,0.074859,1.000000,0.084525,0.299459,0.996792,-0.085389,0.005254
variantName,0.051079,0.065258,-0.049889,0.097972,-0.062918,-0.002543,-0.023676,0.084525,1.000000,-0.037512,0.083713,-0.015299,0.049300
price,-0.075789,-0.181315,-0.077351,-0.422600,-0.120489,-0.034547,-0.007771,0.299459,-0.037512,1.000000,0.299549,-0.148510,0.083875
Registration Year,-0.007783,0.056964,-0.243921,-0.196864,-0.390402,0.090081,0.073661,0.996792,0.083713,0.299549,1.000000,-0.088406,0.002323
Insurance Validity,0.049108,-0.014626,0.036390,0.120762,0.114257,0.037936,0.033188,-0.085389,-0.015299,-0.148510,-0.088406,1.000000,0.000951
Seats,0.005295,-0.299714,0.074924,0.008312,0.010594,0.134449,0.132111,0.005254,0.049300,0.083875,0.002323,0.000951,1.000000

In [15]:
x=df.drop("price",axis=1)
y=df["price"]

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [18]:
x_train.shape

(6695, 12)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [19]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [29]:
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(n_estimators=200,max_depth=52,random_state=0,min_samples_split=3).fit(x_train,y_train)
y_pred=model.predict(x_test)
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(r2_score(y_test,y_pred))

1076496098595.0175
214526.68202239118
0.5960483294925819

In [31]:
from sklearn.linear_model import LinearRegression
model2=LinearRegression().fit(x_train,y_train)
y_pred=model2.predict(x_test)
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(r2_score(y_test,y_pred))

2240532999323.239
556382.7096616807
0.1592472568318073

In [33]:
from sklearn.ensemble import ExtraTreesRegressor
model3=ExtraTreesRegressor().fit(x_train,y_train)
y_pred=model3.predict(x_test)
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(r2_score(y_test,y_pred))

1118195879694.4922
235128.32446833933
0.5804006218446757

In [ ]:
from sklearn.ensemble import ExtraTreesRegressor
model6=ExtraTreesRegressor().fit(x_train,y_train)
y_pred=model6.predict(x_test)
print(r2_score(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

In [27]:

from sklearn.ensemble import RandomForestRegressor
model10 = RandomForestRegressor(n_estimators=100,criterion='squared_error',max_depth=2, random_state=0)
result=model10.fit(x_train, y_train)
y_pred = model10.predict(x_test)
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(r2_score(y_test,y_pred))

2125662553361.7302
527487.065395335
0.20235201921658974

In [ ]:
#overfit to general -hypertune
from sklearn.ensemble import RandomForestRegressor
model2=RandomForestRegressor(n_estimators=2,max_depth=12,random_state=22,min_samples_split=3).fit(x_train,y_train)
y_pred=model2.predict(x_test)
print(r2_score(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

#file mearge